### PR TITLE
minify css and ignore prettier formatting

### PR DESCRIPTION
**Pull request by samagragupta**
#87

### CODE REVIEW

**Comment by 0xnmn** [comment]
app/styles/_custom.scss  is not to be minified. Also not everything in styles should be ignored. 

Ignore all the files expect _custom.scss for now. There can be addition files in future which should not be ignored by prettier or minified.

**Comment by samagragupta** [comment]
@hereisnaman Made the changes in ignored files.

**Comment by 0xnmn** [comment]
> @hereisnaman Made the changes in ignored files.

Please always give your PR a review yourself.

You missed adding app/styles/theme

And custom.scss file is minified which should not be.

**Comment by samagragupta** [comment]
@hereisnaman Done

**Comment by 0xnmn** [comment]
> @hereisnaman Done

Now you left minifying the files inside `/styles/theme`. Please do not hurry to get the PR merged but solve the issue completely.

4 reviews should not be required for such a minor PR.

**Comment by samagragupta** [comment]
@hereisnaman Sorry for such commits. Hope this commit is fine.

**Review by 0xnmn — APPROVED** [review]

**Pull request merged**
