### PR TITLE
Add slug column to CalendarEvent

### LINKED ISSUE #78: [Events] Add Slug to CalendarEvent
1. Write a migration to add `slug` string column to `calendar_events` table which can be null.
2. Update the sequelize model accordingly
3. Update CalendarEvent graphql type
4. Update the AuthorizationPolicy to allow update of the column to organizer and admins and allow read to everyone.
5. Update CalendarEventCreate mutation to auto generate slug from the event title using [slugify](https://www.npmjs.com/package/slugify).
6. Update CalendarEventUpdate mutation to support slug update.
7. Integrate the new column in the view and edit event modals. In the edit modal show an input field below description to edit the slug. The input value should be initialized by the slug of the event.
8. In the view modal, add the slug text at the top linking to `/events/<slug>`.

Please maintain the code quality and naming conventions.

### PR DESCRIPTION
**Pull request by coderrsid**
## Issue
fixes: #78 

Sorry @hereisnaman , had to make a new pull request, the old branch got a little messed up on my side.
I added all the changes you requested in the older pull request.

### CODE REVIEW

**Comment by coderrsid** [comment]
@hereisnaman  i am not able to figure out why it's not receiving the slug in the `ViewEvent` but as i showed you it's there in the event i logged

**Comment by 0xnmn** [comment]
> @hereisnaman i am not able to figure out why it's not receiving the slug in the `ViewEvent` but as i showed you it's there in the event i logged

Because you are not querying it. The slug should be present here: https://github.com/coding-blocks/gondor/blob/master/app/modals/ViewEvent/query.graphql

And similarly for the editmodal also.

But lets better add it to the EventFragment. I'll let you find where EventFragment is defined.

**Comment by coderrsid** [comment]
> > @hereisnaman i am not able to figure out why it's not receiving the slug in the `ViewEvent` but as i showed you it's there in the event i logged
> 
> Because you are not querying it. The slug should be present here: https://github.com/coding-blocks/gondor/blob/master/app/modals/ViewEvent/query.graphql
> 
> And similarly for the editmodal also.
> 
> But lets better add it to the EventFragment. I'll let you find where EventFragment is defined.

Cool. Now i get it. I'll try to add changes.

**Comment by coderrsid** [comment]
Hey @hereisnaman , thanks for helping out. It's working alright now. Please review it. 😄 

final-clip

**Comment by 0xnmn** [comment]
The slug link in ViewModal doesn't look good where it is right now. Move it in the modal body above the from date row and also make the text color primary.

Please also resolve the conflicts.

**Comment by coderrsid** [comment]
> The slug link in ViewModal doesn't look good where it is right now. Move it in the modal body above the from date row and also make the text color primary.
> 
> Please also resolve the conflicts.

Are you talking about this class?
image

**Comment by 0xnmn** [comment]
> > The slug link in ViewModal doesn't look good where it is right now. Move it in the modal body above the from date row and also make the text color primary.
> > Please also resolve the conflicts.
> 
> Are you talking about this class?
> image

`text-primary`

**Comment by coderrsid** [comment]
> `text-primary`

@hereisnaman  Done!

**Comment by 0xnmn** [comment]
> > `text-primary`
> 
> @hereisnaman Done!

You need to add updated screenshots of the ViewModal

**Comment by coderrsid** [comment]
> > > `text-primary`
> > 
> > 
> > @hereisnaman Done!
> 
> You need to add updated screenshots of the ViewModal

image

**Comment by 0xnmn** [comment]
> > > > `text-primary`
> > > 
> > > 
> > > @hereisnaman Done!
> > 
> > 
> > You need to add updated screenshots of the ViewModal
> 
> image

Can't see the slug link text being pink in color.

**Comment by 0xnmn** [comment]
Also please rebase your branch with master.

**Comment by coderrsid** [comment]
image

**Comment by coderrsid** [comment]
> Also please rebase your branch with master.

Do you mean to squash all commits into one commit in this branch?

**Comment by coderrsid** [comment]
> Also please rebase your branch with master.

Done

**Review by 0xnmn — APPROVED** [review]

**Pull request merged**
