### PR TITLE
Expanding Calender Types: Fixes #39

### LINKED ISSUE #39: [Event Types] Map event type with its name
Create a event type - name map [here](https://github.com/coding-blocks/gondor/blob/master/app/components/ColorsList/index.js). Treat the `name` as type and render the actual name rather.

example:
```javascript
{
  OfflineClass: 'Offline Class',
  OnlineClass: 'Online Class',
}
```
image

### PR DESCRIPTION
**Pull request by YashKumarVerma**
Adding expanded names for calender event types

### CODE REVIEW

**Comment by 0xnmn** [comment]
Please add screen shots

**Comment by 0xnmn** [comment]
good work

**Comment by YashKumarVerma** [comment]
I've been facing issues in starting up the application locally.
image

the code changes made were tested as a component.

**Comment by 0xnmn** [comment]
> I've been facing issues in starting up the application locally.
> image
> 
> the code changes made were tested as a component.

Please remove and re-install the node_modules, worked for one student.

**Comment by YashKumarVerma** [comment]
I tried again, also verified cache still same result.

image
I think there is some issue with some global package / webpack config

**Comment by 0xnmn** [comment]
> I tried again, also verified cache still same result.
> 
> image
> I think there is some issue with some global package / webpack config

We can discuss further in the discord channel at https://discord.gg/wNFXjh

**Comment by YashKumarVerma** [comment]
This action was unwanted, updating

**Pull request closed without merging**
