### PR TITLE
Hide appmenu for non admins and members

### PR DESCRIPTION
**Pull request by samagragupta**
#38

### CODE REVIEW

**Comment by 0xnmn** [comment]
adding css doesn't stop component from rendering. Also you don't have to hide all the app emnu components but only on the calendar page which contains the TeamMembers.

**Comment by samagragupta** [comment]
@hereisnaman Do you mean this part?
Capture

**Comment by samagragupta** [comment]
@hereisnaman Also too check for Mobile and Tablets, I think we have to use media query which is in CSS.

**Comment by 0xnmn** [comment]
> @hereisnaman Also too check for Mobile and Tablets, I think we have to use media query which is in CSS.

I have removed the mobile logic from the issue. You can simply not render it for non members now.

**Pull request closed without merging**
