### PR TITLE
Fixes Responsive Size of Username & Avatar

### LINKED ISSUE #27: Proper arrangement of username and image
Capture
IN mobile view: Proper arrangement of username and image

### PR DESCRIPTION
**Pull request by coderrsid**
Fixes #27 

**Explanation** : Actually when i changed the size to mobile-responsive, although the logo wasn't visible but div was present and whatever i tried to set the width of the user-details it just didn't resize for a decent user-name size like mine as you can see below, so i just tried to made the div disappear for a windowWidth <= 500. Please do let me know if something can be changed. 
### Before 
image

### After 
image

### CODE REVIEW

**Comment by coderrsid** [comment]
Please review @hereisnaman ! Thanks 😄

**Comment by 0xnmn** [comment]
Simply use bootstrap classes for it. Closing this.

**Comment by coderrsid** [comment]
@hereisnaman i just want to ask how am i supposed to push the logo `div` by user details as you can see below.. logo isn't there but `div` is present.. i tried using `col-md-4` as you can see to the `div`

Screen-Recording-2020-05-17-at-1 (1)

**Comment by 0xnmn** [comment]
> @hereisnaman i just want to ask how am i supposed to push the logo `div` by user details as you can see below.. logo isn't there but `div` is present.. i tried using `col-md-4` as you can see to the `div`
> 
> Screen-Recording-2020-05-17-at-1 (1)

col-md-2 on the logo div

**Comment by coderrsid** [comment]
> col-md-2 on the logo div

But that just pushes the content in the next line 
image

**Comment by 0xnmn** [comment]
> > col-md-2 on the logo div
> 
> But that just pushes the content in the next line
> image

col-4 col-md-2 on logo div. 

You don't have to remove the col-4. 

Study here https://getbootstrap.com/docs/4.5/layout/grid/

**Pull request closed without merging**
