### PR TITLE
Update type definitions with inline fragments

### LINKED ISSUE #103: [Refactoring] Enclose all protected fields in an inline fragment
For all the type definitions in graphql schema enclose the protected fields inside an inline fragment.

For example `User` type definition in https://github.com/coding-blocks/gondor/blob/master/api/graphql/query/User/type.graphql#L7 can be convert to:
```graphql
type User implements Node {
  id: ID!
  username: String!
  role: UserRoleName!
  firstname: String
  lastname: String
  ... @protected {
    email: String
    mobile_number: String
    photo: String
    events(
      limit: Int
      before: String
      after: String
      exclude: [ID!]
      dateTimeRange: DateTimeRangeInput!
    ): CalendarEventConnection @requireFeature(name: "calendar")
    availability(dateTimeRange: DateTimeRangeInput!): Boolean
  }
}
```

### PR DESCRIPTION
**Pull request by b30wulffz**
## Issue
fixes: #103 

## Solution
Refactored the code with @protected inline fragments

## Screenshots (Desktop)
Not Required

## Screenshots (Mobile)
Not Required

## Checklist
*PR will only be reviewed if the checklist is completed*
- [x] I have done extensive testing for my changes.
- [x] I have self-reviewed my PR and removed all un-necessary changes.
- [x] My changes works well on both desktop and mobile environments.
- [x] I have made sure that my changes solves the actual problem mentioned in the issue.
- [x] The PR contains only 1 commit and have been updated with `master`.

### CODE REVIEW

**Comment by 0xnmn** [comment]
@b30wulffz good PR. No need to enclose in fragment where there is only 1 single protected field.

**Comment by b30wulffz** [comment]
@hereisnaman  If anyone wants to add more fields, this would be helpful. Still, if you want, I can make the required changes.

**Comment by b30wulffz** [comment]
Made changes

> @b30wulffz good PR. No need to enclose in fragment where there is only

**Comment by 0xnmn** [comment]
> @hereisnaman If anyone wants to add more fields, this would be helpful. Still, if you want, I can make the required changes.

If we add more protected fields then we can add a fragment.

**Review by 0xnmn — APPROVED** [review]

**Pull request merged**
